(executables
 (names pbt pipeline_runner ocaml_testsuite_runner)
 (libraries unix qcheck-core qcheck-core.runner checker_common)
 (flags (:standard -w -a))
 (modules pbt pipeline_runner ocaml_testsuite_runner))

(executable
 (name strip_expect_ppx)
 (libraries ppxlib)
 (flags (:standard -w -a))
 (modules strip_expect_ppx))
